/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.gefrase;

import java.io.IOException;
import javax.swing.JTextField;

/**
 * A janela de campos extras
 * 
 * @author Cien
 */
@SuppressWarnings("serial")
public class ExtraFields extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExtraFields.class.getName());

    /**
     * Cria uma nova janela com os campos extras
     * @param parent A janela pai
     */
    public ExtraFields(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        dictionaryName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        recoveryWord = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        verificationCode = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aboutButton = new javax.swing.JMenuItem();

        setTitle("Campos Extras");
        setMinimumSize(new java.awt.Dimension(200, 215));

        jLabel3.setText("Nome do Dicionário:");

        dictionaryName.setEditable(false);
        dictionaryName.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel1.setText("Palavra de Recuperação:");

        recoveryWord.setEditable(false);
        recoveryWord.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel7.setText("Código de Verificação:");

        verificationCode.setEditable(false);
        verificationCode.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jMenu1.setText("Ajuda");

        aboutButton.setText("Sobre");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        jMenu1.add(aboutButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recoveryWord)
                    .addComponent(dictionaryName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(0, 260, Short.MAX_VALUE))
                    .addComponent(verificationCode))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(dictionaryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(recoveryWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(verificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //o botão de sobre
    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        try {
            TextDialog.ofResourceFile(this, "Campos Extras", "extraFields.txt").setVisible(true);
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
            TextDialog.ofThrowable(this, ex).setVisible(true);
        }
    }//GEN-LAST:event_aboutButtonActionPerformed

    /**
     * Retorna o campo do dicionário
     * @return o campo do dicionário
     */
    public JTextField getDictionaryName() {
        return dictionaryName;
    }

    /**
     * Retorna o campo da palavra de recuperação
     * @return o campo da palavra de recuperação
     */
    public JTextField getRecoveryWord() {
        return recoveryWord;
    }
    
    /**
     * Retorna o campo do código de verificação
     * @return o campo do código de verificação
     */
    public JTextField getVerificationCode() {
        return verificationCode;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutButton;
    private javax.swing.JTextField dictionaryName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField recoveryWord;
    private javax.swing.JTextField verificationCode;
    // End of variables declaration//GEN-END:variables
}
