/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.gefrase;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Uma janela para mostrar texto genérico
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class TextDialog extends javax.swing.JDialog {

    /**
     * Mostra o texto de um arquivo no mesmo pacote que a classe da janela
     *
     * @param parent a janela pai
     * @param title o título da janela
     * @param file o arquivo
     * @return a janela de texto
     * @throws IOException se acontecer algum problema durante a leitura do arquivo
     */
    public static TextDialog ofResourceFile(java.awt.Window parent, String title, String file) throws IOException {
        try (InputStream in = TextDialog.class.getResourceAsStream(file)) {
            return new TextDialog(parent, title, new String(in.readAllBytes(), StandardCharsets.UTF_8));
        }
    }

    /**
     * Cria uma janela de texto a partir de uma exception
     *
     * @param parent a janela pai
     * @param t a exception
     * @return a janela de texto
     */
    public static TextDialog ofThrowable(java.awt.Window parent, Throwable t) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (PrintStream stream = new PrintStream(out, true, StandardCharsets.UTF_8)) {
            t.printStackTrace(stream);
            stream.flush();
        }
        return new TextDialog(
                parent,
                "ERR: " + t.getLocalizedMessage(),
                new String(out.toByteArray(), StandardCharsets.UTF_8)
        );
    }

    /**
     * Cria uma nova janela de texto
     *
     * @param parent a janela pai
     * @param title o título da janela
     * @param text o texto
     */
    public TextDialog(java.awt.Window parent, String title, String text) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        setTitle(title);
        this.textArea.setText(text);
        this.textArea.setCaretPosition(0);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveButton = new javax.swing.JMenuItem();
        copyButton = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        printMenu = new javax.swing.JMenu();
        printButtonCutlines = new javax.swing.JMenuItem();
        printButtonNoCutlines = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dialog");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textArea.setRows(5);
        textArea.setTabSize(4);
        textArea.setText("\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"");
        jScrollPane1.setViewportView(textArea);

        jMenu1.setText("Arquivo");

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jMenu1.add(saveButton);

        copyButton.setText("Copiar");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        jMenu1.add(copyButton);
        jMenu1.add(jSeparator1);

        printMenu.setText("Imprimir");

        printButtonCutlines.setText("Com Linhas de Corte");
        printButtonCutlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonCutlinesActionPerformed(evt);
            }
        });
        printMenu.add(printButtonCutlines);

        printButtonNoCutlines.setText("Sem Linhas de Corte");
        printButtonNoCutlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonNoCutlinesActionPerformed(evt);
            }
        });
        printMenu.add(printButtonNoCutlines);

        jMenu1.add(printMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Retorna as seções de texto para impressão
     * @param sectionCutlines se as linhas de corte estão ativadas
     * @return as seções de texto para impressão
     */
    protected String[] getTextSectionsForPrinting(boolean sectionCutlines) {
        return new String[]{this.textArea.getText()};
    }

    //o método de imprimir
    private void printSections(boolean sectionCutlines) {
        try {
            PrintableTextSections t = 
                    new PrintableTextSections(
                            getTextSectionsForPrinting(sectionCutlines), sectionCutlines);
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(t);

            HashPrintRequestAttributeSet e = new HashPrintRequestAttributeSet();
            if (job.printDialog(e)) {
                job.print(e);
            }
        } catch (PrinterException ex) {
            Toolkit.getDefaultToolkit().beep();
            
            ex.printStackTrace(System.err);
            TextDialog.ofThrowable(this, ex).setVisible(true);
        }
    }
    
    //o botão de imprimir texto
    private void printButtonCutlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonCutlinesActionPerformed
        printSections(true);
    }//GEN-LAST:event_printButtonCutlinesActionPerformed

    //o botão de salvar texto
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("Arquivos de Texto (*.txt)", "txt"));
        int result = chooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (file != null) {
                String name = file.getName();
                if (!name.contains(".")) {
                    name = name + ".txt";
                    file = new File(file.getParentFile(), name);
                }
                
                try {
                    Files.writeString(file.toPath(), this.textArea.getText(), StandardCharsets.UTF_8);
                } catch (IOException ex) {
                    Toolkit.getDefaultToolkit().beep();
                    
                    ex.printStackTrace(System.err);
                    TextDialog.ofThrowable(this, ex).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    //o botão de copiar
    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(new StringSelection(this.textArea.getText()), null);
    }//GEN-LAST:event_copyButtonActionPerformed

    private void printButtonNoCutlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonNoCutlinesActionPerformed
        printSections(false);
    }//GEN-LAST:event_printButtonNoCutlinesActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copyButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem printButtonCutlines;
    private javax.swing.JMenuItem printButtonNoCutlines;
    private javax.swing.JMenu printMenu;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
